create table bh_hd_goc_ttuc(
  ma_dvi varchar2(10),
	so_id number,
	so_hd varchar2(20),
	nv varchar2(10),
	phong varchar(20),
	ma_kt varchar(20),
	cb_ql varchar(20),
	ma_kh varchar(20),
	ten_kh nvarchar2(50),
	d_chi_kh nvarchar2(200),
	d_thoai_kh varchar2(20),
	ngay_kt number,
	stbh number,
	phi number,
	stbt number,
	ttuc varchar2(1),
	ttuc_lydo nvarchar2(500),
	ttuc_ttin nvarchar2(500),
	ttuc_nsd varchar2(20),
	ngay_kq number,
	k_qua varchar2(1),
	n_nhan nvarchar2(500),
	g_chu nvarchar2(500),
	so_id_ttuc number,
	kq_nsd varchar2(20)
);