drop table bc_bh_kt_xe;
create table bc_bh_kt_xe(
  id number,
  id_hd Number,
  so_hd varchar2(50),
  ngay_hl Number,
  ngay_kt Number,
  ngay_cap Number,
  taituc varchar2(1),
  kenh_kt varchar2(5),
  ma_kt varchar2(50),
  ten_kt nvarchar2(100),
  nhang_kt varchar2(20),
  tong_dl varchar2(20),
  banca varchar2(1),
  ma_kh varchar2(20),
  ten_kh nvarchar2(200),
  loai_kh varchar2(20),
  ttin_kh nvarchar2(200),
  ma_dvi varchar2(10),
  ma_phong varchar2(20),
  ma_cbo varchar2(20),
  id_dt Number,
  bien_xe varchar2(50),
  so_khung varchar2(50),
  so_may varchar2(50),
  hang_xe varchar2(50),
  hieu_xe varchar2(50),
  ma_bh varchar2(10),
  ma_dt nvarchar2(10),
  xe_kd varchar2(1),
  ttai Number,
  so_cn Number ,
  nam_sx Number,
  nhom_xe varchar2(50),
  nt_stbh varchar2(10),
  stbh Number,
  stbh_qd Number,
  Lh_nv varchar2(10),
  Pt_phi Number,
  nt_phi varchar2(20),
  phi Number,
  phi_qd Number,
  thue Number,
  thue_qd Number,
  constraint khai_thac_xe_p primary key(id)
);